# HomeWork 1 Implementation part

## Ali Noroozbeigy  `9931062`

In [1]:
elements_list = input().split()

C H O


In [2]:
rows = len(elements_list)

In [3]:
equation_split = input().split()

C2 H6 + O2 -> C O2 + H2 O


### each term is a part of equation that we consider a coefficient for it

### each  term is separated by + or ->, so as we iterate over equation and pass one of them, we increase number of columns because columns of augmented matrix are coefficients of equation.

### because there is aleready one term without reaching + or -> , we start from 1

In [4]:
columns = 1

for term in equation_split:
    if term == "+" or term == "->":
        columns += 1
        

In [5]:
import numpy as np

In [6]:
aug_mat = np.zeros((rows, columns + 1))

### in this part, augmented matrix will be filled with indeices of elements. after reaching -> , indices must be calculated with negative signs because they are on the other side of equation

In [7]:
column = 0
sign = 1

for term in equation_split:
    if term == "->":
        column += 1
        sign = -1
    
    elif term == "+":
        column += 1
    
    elif len(term) == 2:
        aug_mat[elements_list.index(term[0]), column] += (sign * float(term[1]))
    
    elif len(term) == 1:
        aug_mat[elements_list.index(term[0]), column] += (sign * 1)        

### and now, augmented matrix will be converted into echelon form according to the algorithm provided in the slides

In [8]:
row = 0
column = 0

while row < rows:
    
    if not np.all(aug_mat[row:, column] == 0):
        first_non_zero_location = np.nonzero(aug_mat[row:, column])[0][0] + row
        
        if first_non_zero_location != row:
            aug_mat[[row, first_non_zero_location]] = aug_mat[[first_non_zero_location, row]]
        
        for i in range(row + 1, rows):
            
            if aug_mat[i, column] != 0:
                m = aug_mat[i, column] / aug_mat[row, column]
                aug_mat[i] -= (m * aug_mat[row])
        
        row +=1
        column +=1
    
    else:
        column += 1

print("Echelon form is : \n\n" + str(aug_mat))        

Echelon form is : 

[[ 2.  0. -1.  0.  0.]
 [ 0.  2. -2. -1.  0.]
 [ 0.  0.  3. -2.  0.]]


### now echelon form will be converted into reduced echelon form according to the algorithm provided in the slides

In [9]:
for row in range(rows-1, -1, -1):
    first_non_zero_location = np.nonzero(aug_mat[row, :])[0][0]
    
    m = 1 / (aug_mat[row, first_non_zero_location])
    aug_mat[row] = m * aug_mat[row]
    
    
    for i in range (row-1, -1, -1):
        m = aug_mat[i, first_non_zero_location] / aug_mat[row, first_non_zero_location]
        
        aug_mat[i] -= (m * aug_mat[row])

print("Reduced Echelon form is : \n\n" + str(aug_mat))         

Reduced Echelon form is : 

[[ 1.          0.          0.         -0.33333333  0.        ]
 [ 0.          1.          0.         -1.16666667  0.        ]
 [ 0.          0.          1.         -0.66666667  0.        ]]


### in this part, basic and free variables will be recognized. the first non zero entry (which is 1) in each row will be regarded as basic ones and other non zere entries in that will be free ones because they didn't changed to zero in the process of converting to reduced echelon form.

### I assigned free variables to one so that basic variables will be caculated easily. the negative sign is because the fact that each basic variable is on the other side of the equation compared to free ones.

In [10]:
basic_vars = {}

for row in range(rows):
    pivot_pos = np.nonzero(aug_mat[row, :])[0][0]
    sum = 0.0
    for entry in aug_mat[row, pivot_pos+1:]:
        sum += entry
    basic_vars[row+1] = (-1 * sum)


result = ""    
for index in range (1, aug_mat.shape[1]):
    
    if index in basic_vars.keys():
        result += "X" + str(index) + " = "+ "{:.2f}".format(basic_vars[index]) + ", "
    else:
        result += "X" + str(index) + " = 1, "

print("The result is: \n\n" + result)        

The result is: 

X1 = 0.33, X2 = 1.17, X3 = 0.67, X4 = 1, 
